In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [4]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

In [7]:
x, y = np.ogrid[:3, :4]
np.where(x < y, x, 10 + y)

array([[10,  0,  0,  0],
       [10, 11,  1,  1],
       [10, 11, 12,  2]])